export const deliveryLinks = {
  uberEats:
    'https://www.ubereats.com/search?q=La%20Pupusa%20Loca%205910%20Bergenline%20Ave%20West%20New%20York%20NJ',
  doorDash:
    'https://www.doordash.com/search/store/La%20Pupusa%20Loca%205910%20Bergenline%20Ave%20West%20New%20York%20NJ/',
  grubhub: 'https://www.grubhub.com/restaurant/la-pupusa-loca-5910-bergenline-ave-west-new-york/10008728',
}

export const menuCategories = [
  {
    id: 'acompanantes',
    title: 'Acompanantes',
    note: 'Sides.',
    items: [
      {
        id: 'arroz-blanco',
        name: 'Arroz Blanco',
        description: 'White rice.',
        price: 3,
      },
      {
        id: 'frijoles',
        name: 'Frijoles',
        description: 'Beans.',
        price: 3.5,
      },
      {
        id: 'casamiento',
        name: 'Casamiento',
        description: 'Rice and beans mixed.',
        price: 3.5,
      },
      {
        id: 'chimol',
        name: 'Chimol',
        description: 'Fresh Salvadoran pico de gallo.',
        price: 3,
      },
      {
        id: 'ensalada-mixta-aguacate',
        name: 'Ensalada Mixta de Aguacate',
        description: 'Mixed salad with avocado.',
        price: 5,
      },
      {
        id: 'ensalada-mixta-side',
        name: 'Ensalada Mixta',
        description: 'Mixed side salad.',
        price: 3.5,
      },
      {
        id: 'french-fries',
        name: 'French Fries',
        description: 'French fries.',
        price: 3.5,
      },
      {
        id: 'frijoles-fritos-alt',
        name: 'Frijoles Fritos.',
        description: 'Fried beans.',
        price: 3.5,
      },
      {
        id: 'fried-cassava',
        name: 'Fried Cassava',
        description: 'Fried cassava.',
        price: 3.5,
      },
      {
        id: 'fried-green-plantains',
        name: 'Fried Green Plantains',
        description: 'Fried green plantains.',
        price: 3.5,
      },
      {
        id: 'fried-sweet-plantains',
        name: 'Fried Sweet Plantains',
        description: 'Fried sweet plantains.',
        price: 3.5,
      },
      {
        id: 'frijoles-fritos',
        name: 'Frijoles Fritos',
        description: 'Fried beans.',
        price: 3.5,
      },
      {
        id: 'habichuelas',
        name: 'Habichuelas',
        description: 'Red beans.',
        price: 3.5,
      },
      {
        id: 'house-salad',
        name: 'House Salad',
        description: 'House salad.',
        price: 3.5,
      },
      {
        id: 'maduros',
        name: 'Maduros',
        description: 'Sweet plantains.',
        price: 3.5,
      },
      {
        id: 'papas-fritas',
        name: 'Papas Fritas',
        description: 'French fries.',
        price: 3.5,
      },
      {
        id: 'tortillas-3',
        name: 'Tortillas (3)',
        description: 'Three warm tortillas.',
        price: 2,
      },
      {
        id: 'tostones',
        name: 'Tostones',
        description: 'Fried green plantains.',
        price: 3.5,
      },
      {
        id: 'arroz-blanco-alt',
        name: 'Arroz Blanco.',
        description: 'White rice.',
        price: 3,
      },
      {
        id: 'yuca-frita',
        name: 'Yuca Frita',
        description: 'Fried cassava.',
        price: 3.5,
      },
      {
        id: 'tortilla-harina-extra',
        name: '1 Tortilla Harina Extra',
        description: 'One extra flour tortilla.',
        price: 1.5,
      },
      {
        id: 'tortilla-harina-remplazo',
        name: '1 Tortilla Harina Remplazo',
        description: 'Flour tortilla replacement.',
        price: 1,
      },
      {
        id: 'aguacate',
        name: 'Aguacate',
        description: 'Avocado side.',
        price: 3.95,
      },
      {
        id: 'chorizo',
        name: 'Chorizo',
        description: 'Salvadoran sausage.',
        price: 3,
      },
      {
        id: 'crema',
        name: 'Crema',
        description: 'Sour cream.',
        price: 2,
      },
      {
        id: 'crema-pequena',
        name: 'Crema Pequena',
        description: 'Small sour cream.',
        price: 1,
      },
      {
        id: 'encurtido',
        name: 'Encurtido',
        description: 'Pickled cabbage salad.',
        price: 1.5,
      },
      {
        id: 'guacamole-sin-tajadas',
        name: 'Guacamole Sin Tajadas',
        description: 'Guacamole without plantain chips.',
        price: 6,
      },
      {
        id: 'huevo-frito',
        name: 'Huevo Frito',
        description: 'Fried egg.',
        price: 1.5,
      },
      {
        id: 'jalapeno',
        name: 'Jalapeno',
        description: 'Jalapeno pepper.',
        price: 1.5,
      },
      {
        id: 'med-container',
        name: 'Med Container',
        description: 'Medium container.',
        price: 2,
      },
      {
        id: 'orden-pan-tostado',
        name: 'Orden de pan tostado',
        description: 'Order of toasted bread.',
        price: 2.5,
      },
      {
        id: 'queso-feta',
        name: 'Queso Feta',
        description: 'Feta cheese.',
        price: 2,
      },
      {
        id: 'queso-salvadoreno',
        name: 'Queso Salvadoreno',
        description: 'Salvadoran cheese.',
        price: 2.5,
      },
      {
        id: 'small-container',
        name: 'Small Container',
        description: 'Small container.',
        price: 1,
      },
      {
        id: 'solo-clara',
        name: 'Solo Clara',
        description: 'Egg whites only.',
        price: 2,
      },
      {
        id: 'sparkling-candle',
        name: 'Sparkling Candle',
        description: 'Sparkling candle.',
        price: 2,
      },
      {
        id: 'tortilla',
        name: 'Tortilla',
        description: 'Single tortilla.',
        price: 1,
      },
      {
        id: 'yuca-herbida',
        name: 'Yuca Herbida.',
        description: 'Boiled cassava.',
        price: 3.5,
      },
    ],
  },
  {
    id: 'aperitivos',
    title: 'Aperitivos',
    note: 'Appetizers and shareables.',
    items: [
      {
        id: 'baleada-con-todo',
        name: 'Baleadas con Todo',
        description: 'Fried beans, scrambled eggs, sour cream, cheese, steak strips, and avocado.',
        price: 6.95,
      },
      {
        id: 'baleada-sencilla',
        name: 'Baleadas Sencillas',
        description: 'Plain baleada.',
        price: 5,
      },
      {
        id: 'calamares-fritos',
        name: 'Calamares Fritos',
        description: 'Fried calamari with French fries.',
        price: 11,
      },
      {
        id: 'ceviche-camaron',
        name: 'Ceviche de Camaron',
        description: 'Shrimp ceviche.',
        price: 14,
      },
      {
        id: 'ceviche-concha-negra',
        name: 'Ceviche de Concha Negra',
        description: 'Black clam ceviche.',
        price: 18,
      },
      {
        id: 'ceviche-mixto',
        name: 'Ceviche Mixto',
        description: 'Mixed seafood ceviche.',
        price: 16,
      },
      {
        id: 'coctel-camarones',
        name: 'Coctel de Camarones',
        description: 'Shrimp cocktail.',
        price: 13.5,
      },
      {
        id: 'conchas-natural',
        name: 'Conchas al Natural',
        description: 'Fresh clams on the half shell.',
        price: 12,
      },
      {
        id: 'enchilada',
        name: 'Enchilada',
        description: 'Chicken or beef on a fried tortilla topped with cabbage and cheese.',
        price: 3.25,
      },
      {
        id: 'guacamole-tajadas',
        name: 'Guacamole con Tajadas',
        description: 'Guacamole with green plantain chips.',
        price: 10.5,
      },
      {
        id: 'pastelitos-pollo-3',
        name: 'Pastelitos de Pollo (3)',
        description: 'Three chicken patties.',
        price: 5.25,
      },
      {
        id: 'picadera-mixta-lg',
        name: 'Picadera Mixta Lg',
        description: 'Large mixed platter.',
        price: 55,
      },
      {
        id: 'picadera-mixta-sm',
        name: 'Picadera Mixta Sm',
        description: 'Small mixed platter.',
        price: 40,
      },
      {
        id: 'platanos-crema',
        name: 'Platanos con Crema',
        description: 'Sweet plantains with sour cream.',
        price: 5,
      },
      {
        id: 'pupusa-chicharron',
        name: 'Pupusa Chicharron',
        description: 'Pork pupusa.',
        price: 2.75,
      },
      {
        id: 'pupusa-chicharron-harina-arroz',
        name: 'Pupusa Chicharron Harina Arroz',
        description: 'Pork pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-frijol',
        name: 'Pupusa Frijol',
        description: 'Bean pupusa.',
        price: 2.75,
      },
      {
        id: 'pupusa-frijol-harina-arroz',
        name: 'Pupusa Frijol Harina Arroz',
        description: 'Bean pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-frijol-queso',
        name: 'Pupusa Frijol y Queso',
        description: 'Bean and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-frijol-queso-harina-arroz',
        name: 'Pupusa Frijol y Queso Harina Arroz',
        description: 'Bean and cheese pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-loroco',
        name: 'Pupusa Loroco',
        description: 'Loroco and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-loroco-harina-arroz',
        name: 'Pupusa Loroco Harina Arroz',
        description: 'Loroco and cheese pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-queso',
        name: 'Pupusa Queso',
        description: 'Cheese pupusa.',
        price: 2.75,
      },
      {
        id: 'pupusa-queso-harina-arroz',
        name: 'Pupusa Queso Harina Arroz',
        description: 'Cheese pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-revuelta',
        name: 'Pupusa Revuelta',
        description: 'Pork, bean, and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-revuelta-harina-arroz',
        name: 'Pupusa Revuelta Harina Arroz',
        description: 'Pork, bean, and cheese pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'taco-pollo-frito',
        name: 'Taco de Pollo Frito',
        description: 'Fried chicken taco.',
        price: 5.5,
      },
      {
        id: 'tacos-pollo-suave-3',
        name: 'Tacos de Pollo Suave (3)',
        description: 'Three soft chicken tacos.',
        price: 11.5,
      },
      {
        id: 'tacos-res-3',
        name: 'Tacos de Res (3)',
        description: 'Three soft steak tacos.',
        price: 11.5,
      },
      {
        id: 'tamal-elote',
        name: 'Tamal de Elote',
        description: 'Corn tamale.',
        price: 3.15,
      },
      {
        id: 'tamal-pollo',
        name: 'Tamal de Pollo',
        description: 'Chicken tamale.',
        price: 3.5,
      },
      {
        id: 'yuca-con-chicharron',
        name: 'Yuca con Chicharron',
        description: 'Fried cassava and pork crackling.',
        price: 12,
      },
      {
        id: 'guacamole-con-chicharron',
        name: 'Guacamole con Chicharron',
        description: 'Guacamole with pork crackling.',
        price: 14,
      },
      {
        id: 'masita-chicharron-solo',
        name: 'Masita de Chicharron Solo',
        description: 'Pork crackling only.',
        price: 10,
      },
      {
        id: 'orden-de-putacos',
        name: 'Orden De Putacos',
        description: 'Putacos order.',
        price: 12,
      },
      {
        id: 'alitas-de-pollo',
        name: 'Alitas De Pollo',
        description: 'Chicken wings with French fries.',
        price: 11.5,
      },
      {
        id: 'pupusa-de-ayote',
        name: 'Pupusa De Ayote',
        description: 'Zucchini and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-de-camaron',
        name: 'Pupusa De Camaron',
        description: 'Shrimp and cheese pupusa.',
        price: 3.5,
      },
      {
        id: 'pupusa-de-chorizo',
        name: 'Pupusa De Chorizo',
        description: 'Chorizo and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-de-jalapeno',
        name: 'Pupusa De Jalapeño',
        description: 'Jalapeno and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-de-pollo',
        name: 'Pupusa De Pollo',
        description: 'Chicken and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-llena-de-amor',
        name: 'Pupusa Llena De Amor',
        description: 'Pupusa filled with love.',
        price: 5,
      },
      {
        id: 'pupusa-mixta',
        name: 'Pupusa Mixta',
        description: 'Mixed pupusa.',
        price: 3.5,
      },
      {
        id: 'pupusa-sliders',
        name: 'Pupusa Sliders',
        description: 'Mini pupusa sliders.',
        price: 8,
      },
    ],
  },
  {
    id: 'batidos',
    title: 'Batidos',
    note: 'Fresh fruit shakes.',
    items: [
      {
        id: 'batido-banana',
        name: 'Batido Banana',
        description: 'Banana shake.',
        price: 6,
      },
      {
        id: 'batido-fresa',
        name: 'Batido Fresa',
        description: 'Strawberry shake.',
        price: 6,
      },
      {
        id: 'batido-guanabana',
        name: 'Batido Guanabana',
        description: 'Soursop shake.',
        price: 6,
      },
      {
        id: 'batido-mamey',
        name: 'Batido Mamey',
        description: 'Mamey shake.',
        price: 6,
      },
      {
        id: 'batido-mango',
        name: 'Batido Mango',
        description: 'Mango shake.',
        price: 6,
      },
      {
        id: 'batido-maracuya',
        name: 'Batido Maracuya',
        description: 'Passion fruit shake.',
        price: 6,
      },
      {
        id: 'batido-mora',
        name: 'Batido Mora',
        description: 'Blackberry shake.',
        price: 6,
      },
      {
        id: 'batido-morir-sonando',
        name: 'Batido Morir Sonando',
        description: 'Orange juice and milk shake.',
        price: 6,
      },
      {
        id: 'batido-papaya',
        name: 'Batido Papaya',
        description: 'Papaya shake.',
        price: 6,
      },
      {
        id: 'batido-trigo',
        name: 'Batido Trigo',
        description: 'Wheat shake.',
        price: 6,
      },
      {
        id: 'batido-chocolate',
        name: 'Batido Chocolate',
        description: 'Chocolate shake.',
        price: 6,
      },
      {
        id: 'batido-vainilla',
        name: 'Batido Vainilla.',
        description: 'Vanilla shake.',
        price: 6,
      },
    ],
  },
  {
    id: 'bebidas-calientes',
    title: 'Bebidas Calientes',
    note: 'Hot drinks.',
    items: [
      {
        id: 'atol-elote',
        name: 'Atol de Elote',
        description: 'Sweet corn drink.',
        price: 5,
      },
      {
        id: 'cafe-con-leche',
        name: 'Cafe con Leche',
        description: 'Coffee with milk.',
        price: 2.25,
      },
      {
        id: 'cafe-espresso',
        name: 'Cafe Espresso',
        description: 'Espresso.',
        price: 1.5,
      },
      {
        id: 'cappuccino',
        name: 'Cappuccino',
        description: 'Cappuccino.',
        price: 3.25,
      },
      {
        id: 'chocolate-caliente',
        name: 'Chocolate Caliente',
        description: 'Hot chocolate.',
        price: 3.25,
      },
      {
        id: 'te',
        name: 'Te',
        description: 'Tea.',
        price: 2,
      },
      {
        id: 'atol-elote-grande',
        name: 'Atol de Elote Grande',
        description: 'Large sweet corn drink.',
        price: 7.25,
      },
      {
        id: 'cafe-con-leche-grande',
        name: 'Cafe con Leche Grande',
        description: 'Large coffee with milk.',
        price: 3.5,
      },
      {
        id: 'cafe-descafeinado',
        name: 'Cafe Descafeinado',
        description: 'Decaf coffee.',
        price: 2,
      },
      {
        id: 'cafe-espresso-alt',
        name: 'Cafe Espresso.',
        description: 'Espresso.',
        price: 1.5,
      },
      {
        id: 'cafe-negro',
        name: 'Cafe Negro',
        description: 'Black coffee.',
        price: 2,
      },
      {
        id: 'cafe-negro-grande',
        name: 'Cafe Negro Grande',
        description: 'Large black coffee.',
        price: 3,
      },
      {
        id: 'cortadito',
        name: 'Cortadito',
        description: 'Cortadito coffee.',
        price: 2.5,
      },
      {
        id: 'te-lipton',
        name: 'Te Lipton',
        description: 'Lipton tea.',
        price: 2,
      },
      {
        id: 'te-lipton-grande',
        name: 'Te Lipton Grande',
        description: 'Large Lipton tea.',
        price: 3,
      },
      {
        id: 'te-manzanilla',
        name: 'Te Manzanilla',
        description: 'Chamomile tea.',
        price: 2,
      },
      {
        id: 'te-manzanilla-grande',
        name: 'Te Manzanilla Grande',
        description: 'Large chamomile tea.',
        price: 3,
      },
      {
        id: 'te-verde',
        name: 'Te Verde',
        description: 'Green tea.',
        price: 2,
      },
      {
        id: 'te-verde-grande',
        name: 'Te Verde Grande',
        description: 'Large green tea.',
        price: 3,
      },
    ],
  },
  {
    id: 'bebidas-frias',
    title: 'Bebidas Frias',
    note: 'Cold drinks and sodas.',
    items: [
      {
        id: '7up',
        name: '7up',
        description: '7up soda.',
        price: 2,
      },
      {
        id: 'botella-agua',
        name: 'Botella de Agua',
        description: 'Bottled water.',
        price: 1.5,
      },
      {
        id: 'clamato',
        name: 'Clamato',
        description: 'Clamato drink.',
        price: 3,
      },
      {
        id: 'coca-cola',
        name: 'Coca Cola',
        description: 'Coca Cola soda.',
        price: 2,
      },
      {
        id: 'colombiana',
        name: 'Colombiana',
        description: 'Colombiana soda.',
        price: 2.5,
      },
      {
        id: 'diet-coke',
        name: 'Diet Coke',
        description: 'Diet Coke.',
        price: 2,
      },
      {
        id: 'ginger-ale',
        name: 'Ginger Ale',
        description: 'Ginger Ale.',
        price: 2,
      },
      {
        id: 'jarritos',
        name: 'Jarritos',
        description: 'Mexican Jarritos soda.',
        price: 2.5,
      },
      {
        id: 'kolashapan',
        name: 'Kolashapan',
        description: 'Salvadoran Kolashapan.',
        price: 2.5,
      },
      {
        id: 'pepsi',
        name: 'Pepsi',
        description: 'Pepsi soda.',
        price: 2,
      },
      {
        id: 'snapple',
        name: 'Snapple',
        description: 'Snapple drink.',
        price: 2.5,
      },
      {
        id: 'sprite',
        name: 'Sprite',
        description: 'Sprite soda.',
        price: 2,
      },
      {
        id: 'sunkist',
        name: 'Sunkist',
        description: 'Sunkist soda.',
        price: 2,
      },
      {
        id: 'vaso-leche',
        name: 'Vaso con Leche',
        description: 'Glass of milk.',
        price: 2.5,
      },
      {
        id: 'welchs',
        name: 'Welchs',
        description: 'Welchs juice.',
        price: 2.5,
      },
      {
        id: 'club-soda',
        name: 'Club soda',
        description: 'Club soda.',
        price: 2,
      },
    ],
  },
  {
    id: 'camarones',
    title: 'Camarones',
    note: 'Shrimp entrees.',
    items: [
      {
        id: 'camarones-ajillo',
        name: 'Camarones al Ajillo',
        description: 'Shrimp in garlic sauce.',
        price: 17,
      },
      {
        id: 'camarones-vino',
        name: 'Camarones al Vino',
        description: 'Shrimp in white wine sauce.',
        price: 17,
      },
      {
        id: 'camarones-asados',
        name: 'Camarones Asados',
        description: 'Grilled shrimp.',
        price: 17,
      },
      {
        id: 'camarones-champinones',
        name: 'Camarones con Champinones',
        description: 'Shrimp with mushrooms.',
        price: 18,
      },
      {
        id: 'camarones-empanizados',
        name: 'Camarones Empanizados',
        description: 'Breaded shrimp.',
        price: 16,
      },
      {
        id: 'camarones-enchilados',
        name: 'Camarones Enchilados',
        description: 'Shrimp in spicy tomato sauce.',
        price: 16.25,
      },
      {
        id: 'camarones-fritos',
        name: 'Camarones Fritos',
        description: 'Fried shrimp.',
        price: 17,
      },
      {
        id: 'mofongo-camarones-ajillo',
        name: 'Mofongo Camarones Al Ajillo',
        description: 'Mofongo with garlic shrimp.',
        price: 19.95,
      },
      {
        id: 'camarones-salteados',
        name: 'Camarones Salteados',
        description: 'Sauteed shrimp.',
        price: 17,
      },
    ],
  },
  {
    id: 'carnes',
    title: 'Carnes',
    note: 'Meat entrees.',
    items: [
      {
        id: 'bistec-higado',
        name: 'Bistec de Higado',
        description: 'Liver steak with onions.',
        price: 16.95,
      },
      {
        id: 'bistec-palomilla',
        name: 'Bistec de Palomilla',
        description: 'Palomilla steak.',
        price: 16.95,
      },
      {
        id: 'bistec-salteado',
        name: 'Bistec Salteado',
        description: 'Sauteed steak strips.',
        price: 17.25,
      },
      {
        id: 'carne-plancha',
        name: 'Carne a la Plancha',
        description: 'Grilled steak.',
        price: 15.95,
      },
      {
        id: 'carne-empanizada',
        name: 'Carne Empanizada',
        description: 'Breaded steak.',
        price: 16.95,
      },
      {
        id: 'churrasco',
        name: 'Churrasco',
        description: 'Grilled skirt steak.',
        price: 29.5,
      },
      {
        id: 'churrasquito-camaron-salteado',
        name: 'Churrasquito y Camaron Salteado',
        description: 'Skirt steak and sauteed shrimp.',
        price: 24.95,
      },
      {
        id: 'mar-y-tierra',
        name: 'Mar y Tierra',
        description: 'Grilled skirt steak and shrimp.',
        price: 30,
      },
      {
        id: 'mofongo-mar-tierra',
        name: 'Mofongo Mar y Tierra',
        description: 'Mofongo surf and turf.',
        price: 25,
      },
    ],
  },
  {
    id: 'combinaciones-dia',
    title: 'Combinaciones del Dia',
    note: 'Daily combinations.',
    items: [
      {
        id: 'bandeja-paisa',
        name: 'Bandeja Paisa',
        description: 'Grilled steak, sausage, pork crackling, sweet plantains, white rice, eggs, avocado, and beans.',
        price: 25,
      },
      {
        id: 'churrasco-carne-adobada',
        name: 'Churrasco y Carne Adobada',
        description: 'Skirt steak and marinated pork.',
        price: 26,
      },
      {
        id: 'parrillada-especial',
        name: 'Parrillada Especial',
        description: 'Special grilled platter.',
        price: 24.5,
      },
      {
        id: 'plato-tipico-salvadoreno',
        name: 'Plato Tipico Salvadoreno',
        description: 'Typical Salvadoran platter.',
        price: 16,
      },
      {
        id: 'pollo-carne-plancha',
        name: 'Pollo y Carne a la Plancha',
        description: 'Grilled chicken and steak platter.',
        price: 18.95,
      },
    ],
  },
  {
    id: 'desayunos',
    title: 'Desayunos',
    note: 'Breakfast plates.',
    items: [
      {
        id: 'fourth-july-pancakes',
        name: '4th of July Pancakes',
        description: 'Independence Day pancakes.',
        price: 10,
      },
      {
        id: 'fourth-july-waffles',
        name: '4th of July Waffles',
        description: 'Independence Day waffles.',
        price: 10,
      },
      {
        id: 'avocado-toast',
        name: 'Avocado Toast',
        description: 'Avocado toast.',
        price: 8.5,
      },
      {
        id: 'big-breakfast',
        name: 'Big Breakfast',
        description: 'Big breakfast plate.',
        price: 12,
      },
      {
        id: 'burrito-salvadoreno',
        name: 'Burrito Salvadoreno',
        description: 'Salvadoran breakfast burrito.',
        price: 10.5,
      },
      {
        id: 'buttermilk-pancakes-3',
        name: 'Buttermilk Pancakes (3)',
        description: 'Three buttermilk pancakes.',
        price: 8,
      },
      {
        id: 'chunky-monkey-pancakes-alt',
        name: 'Chuncky Monkey Pancakes',
        description: 'Banana, chocolate chip, and nut pancakes.',
        price: 10,
      },
      {
        id: 'desayuno-ca-carne',
        name: 'Desayuno CA con Carne',
        description: 'Central American breakfast with meat.',
        price: 12,
      },
      {
        id: 'desayuno-con-tamal',
        name: 'Desayuno con Tamal',
        description: 'Breakfast with tamale.',
        price: 11,
      },
      {
        id: 'desayuno-pericos',
        name: 'Desayuno Pericos',
        description: 'Scrambled eggs with onions and tomatoes.',
        price: 10.5,
      },
      {
        id: 'desayuno-salvadoreno',
        name: 'Desayuno Salvadoreno',
        description: 'Eggs, beans, plantains, avocado, cheese, and tortilla.',
        price: 11.25,
      },
      {
        id: 'desayuno-tipico-carne',
        name: 'Desayuno Tipico con Carne',
        description: 'Typical breakfast with meat.',
        price: 12,
      },
      {
        id: 'french-toast',
        name: 'French Toast',
        description: 'French toast.',
        price: 8,
      },
      {
        id: 'fruity-pebbles-waffles',
        name: 'Fruity Pebbles Waffles',
        description: 'Waffles with Fruity Pebbles.',
        price: 10,
      },
      {
        id: 'huevos-rancheros',
        name: 'Huevos Rancheros',
        description: 'Ranch-style eggs.',
        price: 10,
      },
      {
        id: 'huevos-revueltos-jamon',
        name: 'Huevos Revueltos con Jamon',
        description: 'Scrambled eggs with ham.',
        price: 9.5,
      },
      {
        id: 'huevos-revueltos-pupusa',
        name: 'Huevos Revueltos con Pupusa',
        description: 'Scrambled eggs with pupusa.',
        price: 11,
      },
      {
        id: 'mini-pancakes-10',
        name: 'Mini Pancakes 10',
        description: 'Ten mini pancakes.',
        price: 8,
      },
      {
        id: 'mini-pancakes-5',
        name: 'Mini Pancakes 5',
        description: 'Five mini pancakes.',
        price: 5,
      },
      {
        id: 'nutella-french-toast',
        name: 'Nutella French Toast',
        description: 'French toast with Nutella.',
        price: 10,
      },
      {
        id: 'oatmeal',
        name: 'Oatmeal',
        description: 'Oatmeal bowl.',
        price: 5,
      },
      {
        id: 'pancake-lovers-dream',
        name: 'Pancake Lover\'s Dream',
        description: 'Assorted pancakes platter.',
        price: 12,
      },
      {
        id: 'strawberry-shortcake-waffles',
        name: 'Strawberry Shortcake Waffles',
        description: 'Waffles with strawberries and cream.',
        price: 10,
      },
      {
        id: 'banana-pancakes',
        name: 'Banana Pancackes',
        description: 'Banana pancakes.',
        price: 9,
      },
      {
        id: 'chunky-monkey-pancakes',
        name: 'Chunky Monkey Pancakes',
        description: 'Banana, chocolate chip, and nut pancakes.',
        price: 10,
      },
      {
        id: 'desayuno-ca-sin-carne',
        name: 'Desayuno CA Sin Carne',
        description: 'Central American breakfast without meat.',
        price: 10,
      },
      {
        id: 'oatmeal-fruits',
        name: 'Oatmeal W/Fruits',
        description: 'Oatmeal with fresh fruits.',
        price: 6.5,
      },
      {
        id: 'strawberry-shortcake-waffles-alt',
        name: 'Strawberry ShorWaffles.',
        description: 'Strawberry shortcake waffles.',
        price: 10,
      },
    ],
  },
  {
    id: 'ensaladas',
    title: 'Ensaladas',
    note: 'Fresh salads.',
    items: [
      {
        id: 'ens-camaron-calamar',
        name: 'Ens de Camaron y Calamar',
        description: 'Shrimp and calamari salad.',
        price: 16.25,
      },
      {
        id: 'ensalada-churrasquito',
        name: 'Ensalada de Churrasquito',
        description: 'Grilled steak salad.',
        price: 12.5,
      },
      {
        id: 'ensalada-pechuga',
        name: 'Ensalada de Pechuga',
        description: 'Grilled chicken breast salad.',
        price: 12.5,
      },
      {
        id: 'ensalada-salmon',
        name: 'Ensalada de Salmon',
        description: 'Grilled salmon salad.',
        price: 16.95,
      },
      {
        id: 'ensalada-mar-tierra',
        name: 'Ensalada Mar y Tierra',
        description: 'Grilled shrimp and steak salad.',
        price: 17.25,
      },
    ],
  },
  {
    id: 'jugos-naturales',
    title: 'Jugos Naturales',
    note: 'Natural juices and drinks.',
    items: [
      {
        id: 'jugo-natural-cebada',
        name: 'Jugo Natural Cebada',
        description: 'Barley drink.',
        price: 5,
      },
      {
        id: 'jugo-natural-chan',
        name: 'Jugo Natural Chan',
        description: 'Chan seed drink.',
        price: 5,
      },
      {
        id: 'jugo-natural-horchata',
        name: 'Jugo Natural Horchata',
        description: 'House horchata drink.',
        price: 5,
      },
      {
        id: 'jugo-natural-limonada',
        name: 'Jugo Natural Limonada',
        description: 'Fresh lemonade.',
        price: 5,
      },
      {
        id: 'jugo-natural-maracuya',
        name: 'Jugo Natural Maracuya',
        description: 'Passion fruit drink.',
        price: 5,
      },
      {
        id: 'jugo-natural-maranon',
        name: 'Jugo Natural Maranon',
        description: 'Cashew fruit drink.',
        price: 5,
      },
      {
        id: 'jugo-natural-naranja',
        name: 'Jugo Natural Naranja',
        description: 'Fresh orange juice.',
        price: 6,
      },
      {
        id: 'jugo-natural-tamarindo',
        name: 'Jugo Natural Tamarindo',
        description: 'Tamarind drink.',
        price: 5,
      },
      {
        id: 'jugo-natural-zanahoria',
        name: 'Jugo Natural Zanahoria',
        description: 'Carrot juice.',
        price: 6,
      },
      {
        id: 'galon-cebada',
        name: 'Galon Cebada',
        description: 'Gallon of barley drink.',
        price: 18,
      },
      {
        id: 'galon-chan',
        name: 'Galon Chan',
        description: 'Gallon of chan drink.',
        price: 18,
      },
      {
        id: 'galon-horchata',
        name: 'Galon Horchata',
        description: 'Gallon of horchata drink.',
        price: 18,
      },
      {
        id: 'galon-maracuya',
        name: 'Galon Maracuya',
        description: 'Gallon of passion fruit drink.',
        price: 18,
      },
      {
        id: 'galon-maranon',
        name: 'Galon Maranon',
        description: 'Gallon of cashew fruit drink.',
        price: 18,
      },
      {
        id: 'galon-tamarindo',
        name: 'Galon Tamarindo',
        description: 'Gallon of tamarind drink.',
        price: 18,
      },
    ],
  },
  {
    id: 'mariscos',
    title: 'Mariscos',
    note: 'Seafood entrees.',
    items: [
      {
        id: 'filete-plancha',
        name: 'Filete a la Plancha',
        description: 'Grilled fish fillet.',
        price: 17,
      },
      {
        id: 'filete-vino',
        name: 'Filete al Vino',
        description: 'Fish fillet in white wine sauce.',
        price: 17,
      },
      {
        id: 'filete-empanizado',
        name: 'Filete Empanizado',
        description: 'Breaded fish fillet.',
        price: 16.25,
      },
      {
        id: 'filete-pescado-frito',
        name: 'Filete Pescado Frito',
        description: 'Fried fish fillet.',
        price: 17,
      },
      {
        id: 'filete-camarones-vino',
        name: 'Filete y Camarones al Vino',
        description: 'Fish fillet and shrimp in wine sauce.',
        price: 18,
      },
      {
        id: 'langosta-entomatada',
        name: 'Langosta Entomatada',
        description: 'Lobster in tomato sauce.',
        price: 35,
      },
      {
        id: 'langosta-rellena-camarones',
        name: 'Langosta Rellena con Camarones',
        description: 'Stuffed lobster with shrimp.',
        price: 70,
      },
      {
        id: 'mojarra-frita',
        name: 'Mojarra Frita',
        description: 'Fried tilapia.',
        price: 17.95,
      },
      {
        id: 'pargo-vino',
        name: 'Pargo al Vino',
        description: 'Red snapper in wine sauce.',
        price: 18.95,
      },
      {
        id: 'pargo-camarones',
        name: 'Pargo con Camarones',
        description: 'Red snapper with shrimp.',
        price: 22,
      },
      {
        id: 'pargo-frito',
        name: 'Pargo Frito',
        description: 'Fried red snapper.',
        price: 18.95,
      },
      {
        id: 'salmon-plancha',
        name: 'Salmon a la Plancha',
        description: 'Grilled salmon.',
        price: 17.5,
      },
      {
        id: 'salmon-tropical-camarones',
        name: 'Salmon Tropical con Camarones',
        description: 'Salmon with tropical sauce and shrimp.',
        price: 22,
      },
    ],
  },
  {
    id: 'menu-ninos',
    title: 'Menu Ninos',
    note: 'Kids menu.',
    items: [
      {
        id: 'deditos-pollo',
        name: 'Deditos de Pollo',
        description: 'Chicken fingers.',
        price: 10,
      },
      {
        id: 'salchipapas',
        name: 'Salchipapas',
        description: 'Fried hot dog bits with French fries.',
        price: 9.25,
      },
      {
        id: 'trocitos-carne-papitas',
        name: 'Trocitos de Carne con Papitas',
        description: 'Steak bits with fries.',
        price: 10.25,
      },
      {
        id: 'trocitos-carne-pupusa',
        name: 'Trocitos de Carne con Pupusa',
        description: 'Steak bits with pupusa.',
        price: 10.25,
      },
      {
        id: 'trocitos-pollo-papitas',
        name: 'Trocitos de Pollo con Papitas',
        description: 'Chicken bits with fries.',
        price: 9.25,
      },
      {
        id: 'choripapas',
        name: 'Choripapas',
        description: 'Choripapas.',
        price: 9.25,
      },
    ],
  },
  {
    id: 'pollo',
    title: 'Pollo',
    note: 'Chicken entrees.',
    items: [
      {
        id: 'chicharron-pollo',
        name: 'Chicharron de Pollo',
        description: 'Chicken cracklings.',
        price: 14,
      },
      {
        id: 'pechuga-hawaiana',
        name: 'Pechuga a la Hawaiana',
        description: 'Hawaiian chicken breast.',
        price: 16.95,
      },
      {
        id: 'pechuga-plancha',
        name: 'Pechuga a la Plancha',
        description: 'Grilled chicken breast.',
        price: 15,
      },
      {
        id: 'pechuga-vino-blanco',
        name: 'Pechuga al Vino Blanco',
        description: 'Chicken breast in white wine.',
        price: 17,
      },
      {
        id: 'pechuga-champinones',
        name: 'Pechuga con Champinones',
        description: 'Chicken breast with mushrooms.',
        price: 16.95,
      },
      {
        id: 'pechuga-empanizada',
        name: 'Pechuga Empanizada',
        description: 'Breaded chicken breast.',
        price: 16,
      },
      {
        id: 'pechuga-encebollada',
        name: 'Pechuga Encebollada',
        description: 'Chicken breast with sauteed onions.',
        price: 16,
      },
      {
        id: 'pechuga-salteada',
        name: 'Pechuga Salteada',
        description: 'Sauteed chicken breast.',
        price: 14.95,
      },
      {
        id: 'pollo-camaron-asado',
        name: 'Pollo y Camaron Asado',
        description: 'Grilled chicken and shrimp.',
        price: 22,
      },
      {
        id: 'pollo-camaron-vino',
        name: 'Pollo y Camaron al Vino',
        description: 'Chicken and shrimp in wine sauce.',
        price: 22,
      },
      {
        id: 'pollo-tajadas',
        name: 'Pollo con Tajadas',
        description: 'Chicken with green plantain slices.',
        price: 15,
      },
    ],
  },
  {
    id: 'cerdo',
    title: 'CERDO',
    note: 'Pork entrees.',
    items: [
      {
        id: 'chuletas-cerdo',
        name: 'Chuletas de Cerdo',
        description: 'Pork chops.',
        price: 14.95,
      },
      {
        id: 'lomo-hawaiana',
        name: 'Lomo a la Hawaiana',
        description: 'Hawaiian pork loin.',
        price: 16,
      },
      {
        id: 'lomo-cerdo-plancha',
        name: 'Lomo de Cerdo a la Plancha',
        description: 'Grilled pork loin.',
        price: 14.25,
      },
      {
        id: 'lomo-cerdo-champinones',
        name: 'Lomo de Cerdo con Champinones',
        description: 'Pork loin with mushrooms.',
        price: 15,
      },
      {
        id: 'lomo-cerdo-empanizado',
        name: 'Lomo de Cerdo Empanizado',
        description: 'Breaded pork loin.',
        price: 14.5,
      },
    ],
  },
  {
    id: 'postres',
    title: 'Postres',
    note: 'Desserts.',
    items: [
      {
        id: 'chocolate-cake',
        name: 'Chocolate Cake',
        description: 'Chocolate cake.',
        price: 6,
      },
      {
        id: 'empanada-platano-3',
        name: 'Empanada de Platano (3)',
        description: 'Three plantain empanadas.',
        price: 6,
      },
      {
        id: 'flan',
        name: 'Flan',
        description: 'Caramel flan.',
        price: 6,
      },
      {
        id: 'ice-cream-vainilla',
        name: 'Ice Cream Vainilla',
        description: 'Vanilla ice cream.',
        price: 4,
      },
      {
        id: 'mango-verde',
        name: 'Mango Verde',
        description: 'Green mango slice.',
        price: 5,
      },
      {
        id: 'nuegados-chilate-3',
        name: 'Nuegados con Chilate (3)',
        description: 'Three nuegados with chilate.',
        price: 6,
      },
      {
        id: 'oreo-cheesecake',
        name: 'Oreo Cheesecake',
        description: 'Oreo cheesecake.',
        price: 6,
      },
      {
        id: 'quesadilla-salvadorena',
        name: 'Quesadilla Salvadorena',
        description: 'Salvadoran quesadilla cake.',
        price: 5,
      },
      {
        id: 'strawberry-cheesecake',
        name: 'Strawberry Cheesecake',
        description: 'Strawberry cheesecake.',
        price: 6,
      },
      {
        id: 'tiramisu',
        name: 'Tiramisu',
        description: 'Tiramisu.',
        price: 6,
      },
      {
        id: 'tres-leches',
        name: 'Tres Leches',
        description: 'Tres leches cake.',
        price: 6,
      },
      {
        id: 'ice-cream-chocolate',
        name: 'Ice Cream Chocolate',
        description: 'Chocolate ice cream.',
        price: 4,
      },
      {
        id: 'ice-cream-fresa',
        name: 'Ice Cream Fresa',
        description: 'Strawberry ice cream.',
        price: 4,
      },
      {
        id: 'nuegados-sin-chilate-3',
        name: 'Nuegados Sin Chilate (3).',
        description: 'Three nuegados without chilate.',
        price: 6,
      },
    ],
  },
  {
    id: 'sandwiches',
    title: 'Sandwiches',
    note: 'Sandwiches.',
    items: [
      {
        id: 'panes-rellenos',
        name: 'Panes Rellenos',
        description: 'Stuffed Salvadoran sandwich.',
        price: 11.25,
      },
      {
        id: 'sandwich-bistec',
        name: 'Sandwich de Bistec',
        description: 'Steak sandwich.',
        price: 11.5,
      },
      {
        id: 'sand-huevo-rev-jamon',
        name: 'Sand de Huevo Rev c/Jamon',
        description: 'Scrambled egg and ham sandwich.',
        price: 9,
      },
      {
        id: 'sandwich-jamon-queso',
        name: 'Sandwich de Jamon y Queso',
        description: 'Ham and cheese sandwich.',
        price: 11.25,
      },
      {
        id: 'sandwich-pez-emp',
        name: 'Sandwich de Pez Emp',
        description: 'Breaded fish sandwich.',
        price: 11.25,
      },
      {
        id: 'sandwich-pollo',
        name: 'Sandwich de Pollo',
        description: 'Chicken sandwich.',
        price: 11.25,
      },
      {
        id: 'sandwich-bistec-empanizado',
        name: 'Sandwich de Bistec/Empanizado',
        description: 'Breaded steak sandwich.',
        price: 12,
      },
      {
        id: 'sand-pollo-empanizado',
        name: 'Sand. de Pollo Empanizado.',
        description: 'Breaded chicken sandwich.',
        price: 11.75,
      },
    ],
  },
  {
    id: 'sopas',
    title: 'Sopas',
    note: 'Soups served with tortillas or rice.',
    items: [
      {
        id: 'sopa-camarones',
        name: 'Sopa de Camarones',
        description: 'Shrimp soup.',
        price: 18,
      },
      {
        id: 'sopa-mariscos',
        name: 'Sopa de Mariscos',
        description: 'Seafood soup.',
        price: 30,
      },
      {
        id: 'sopa-mondongo',
        name: 'Sopa de Mondongo',
        description: 'Tripe soup.',
        price: 11.25,
      },
      {
        id: 'sopa-pescado',
        name: 'Sopa de Pescado',
        description: 'Fish soup.',
        price: 17,
      },
      {
        id: 'sopa-pollo',
        name: 'Sopa de Pollo',
        description: 'Chicken soup.',
        price: 11.25,
      },
      {
        id: 'sopa-res',
        name: 'Sopa de Res',
        description: 'Beef soup.',
        price: 11.25,
      },
    ],
  },
]
