export const deliveryLinks = {
  uberEats:
    'https://www.ubereats.com/search?q=Pupusa%20Loca%20197%20Market%20St%20Paterson%20NJ',
  doorDash:
    'https://www.doordash.com/search/store/Pupusa%20Loca%20197%20Market%20St%20Paterson%20NJ/',
  grubhub: 'https://www.grubhub.com/restaurant/pupusa-loca-197-market-st-paterson/2692338',
}

export const menuCategories = [
  {
    id: 'pupusas-tipicos',
    title: 'Pupusas & Tipicos',
    note: 'Traditional Salvadoran favorites.',
    items: [
      {
        id: 'pupusa-1-ingredient',
        name: 'Pupusa 1 Ingredient',
        description: 'Choose cheese, beans, or chicharron.',
        price: 2.75,
      },
      {
        id: 'pupusa-2-ingredients',
        name: 'Pupusa 2 Ingredients',
        description: 'Classic mixed pupusa combinations.',
        price: 3,
      },
      {
        id: 'pupusa-arroz-2',
        name: 'Rice Pupusa 2 Ingredients',
        description:
          'Revueltas, beans with cheese, loroco with cheese, chicken with cheese, ayote with cheese, jalapeno with cheese, or shrimp with cheese.',
        price: 3.5,
      },
      {
        id: 'pupusa-3-ingredients',
        name: 'Pupusa 3 Ingredients',
        description: 'Three-ingredient pupusa made to order.',
        price: 3.25,
      },
      {
        id: 'pupusa-arroz-3',
        name: 'Rice Pupusa 3 Ingredients',
        description: 'Mixed beans, chicharron, and cheese, or cheese, beans, and loroco.',
        price: 3.25,
      },
      {
        id: 'burrito-grande',
        name: 'Burrito Grande de Carne o Pollo',
        description: 'Steak or chicken with rice and beans, topped with tomato sauce, cheese, and cilantro.',
        price: 12,
      },
      {
        id: 'plato-tipico',
        name: 'Plato Tipico',
        description: 'Popular platter with pupusa, tamal, enchilada, and fried taco.',
        price: 16,
      },
      {
        id: 'enchiladas',
        name: 'Enchiladas',
        description: 'Chicken or beef on a fried tortilla topped with cabbage, cheese, and boiled egg.',
        price: 3.25,
      },
      {
        id: 'baleada-tortilla',
        name: 'Baleada Tortilla',
        description: 'Fried beans, scrambled eggs, sour cream, cheese, steak strips, and avocado.',
        price: 6.95,
      },
      {
        id: 'baleada-sencilla',
        name: 'Baleada Sencilla',
        description: 'Plain baleada.',
        price: 5,
      },
      {
        id: 'tacos-fritos',
        name: '2 Tacos Fritos',
        description: 'Fried chicken or beef tacos.',
        price: 5.5,
      },
      {
        id: 'tamal-cerdo',
        name: 'Tamal de Cerdo',
        description: 'Pork tamale.',
        price: 3.5,
      },
      {
        id: 'tamal-pollo',
        name: 'Tamal de Pollo',
        description: 'Chicken tamale.',
        price: 3.5,
      },
      {
        id: 'tamal-elote',
        name: 'Tamal de Elote con Crema',
        description: 'Sweet corn tamale with sour cream.',
        price: 3.15,
      },
      {
        id: 'platano-crema',
        name: 'Platano Maduro con Crema',
        description: 'Sweet plantains with sour cream.',
        price: 5,
      },
      {
        id: 'platano-frijol-crema',
        name: 'Platano Maduro con Frijol y Crema',
        description: 'Sweet plantains with fried beans and sour cream.',
        price: 6.5,
      },
      {
        id: 'tacos-suaves',
        name: '3 Tacos Suaves',
        description: 'Soft chicken or beef tacos.',
        price: 11.5,
      },
      {
        id: 'pasteles',
        name: '2 Pasteles de Pollo o Cerdo',
        description: 'Chicken or pork patties.',
        price: 5.25,
      },
    ],
  },
  {
    id: 'desayunos',
    title: 'Desayunos',
    note: 'Breakfast plates.',
    items: [
      {
        id: 'desayuno-chapin',
        name: 'Desayuno Chapin',
        description:
          'Fried eggs topped with tomato sauce, fried beans, avocado, sour cream, cheese, and tortilla.',
        price: 10.95,
      },
      {
        id: 'desayuno-guanaco',
        name: 'Desayuno Guanaco',
        description: 'Scrambled eggs, fried beans, avocado, sour cream, sausage, cheese, and tortilla.',
        price: 11.25,
      },
      {
        id: 'desayuno-catracho',
        name: 'Desayuno Catracho',
        description:
          'Scrambled eggs, fried beans, sweet plantains, avocado, sour cream, cheese, sausage, and tortilla.',
        price: 11.5,
      },
    ],
  },
  {
    id: 'sopas',
    title: 'Sopas',
    note: 'Served with rice or 2 tortillas.',
    items: [
      {
        id: 'sopa-res-small',
        name: 'Sopa de Res',
        description: 'Beef soup with vegetables. Small.',
        price: 6.25,
      },
      {
        id: 'sopa-res-large',
        name: 'Sopa de Res',
        description: 'Beef soup with vegetables. Large.',
        price: 11.25,
      },
      {
        id: 'sopa-gallina-small',
        name: 'Sopa de Gallina',
        description: 'Chicken soup with vegetables. Small.',
        price: 6.25,
      },
      {
        id: 'sopa-gallina-large',
        name: 'Sopa de Gallina',
        description: 'Chicken soup with vegetables. Large.',
        price: 11.25,
      },
      {
        id: 'sopa-mondongo-small',
        name: 'Sopa de Mondongo',
        description: 'Tripe soup with vegetables. Small.',
        price: 6.25,
      },
      {
        id: 'sopa-mondongo-large',
        name: 'Sopa de Mondongo',
        description: 'Tripe soup with vegetables. Large.',
        price: 11.25,
      },
      {
        id: 'sopa-mariscos-especial',
        name: 'Sopa de Mariscos Especiales',
        description: 'Seafood special soup, cream or broth.',
        price: 30,
      },
    ],
  },
  {
    id: 'aperitivos',
    title: 'Aperitivos',
    note: 'Appetizers and shareables.',
    items: [
      {
        id: 'calamares-fritos',
        name: 'Calamares Fritos',
        description: 'Fried calamari with french fries.',
        price: 11,
      },
      {
        id: 'calamares-pupusa-loca',
        name: 'Calamares Pupusa Loca',
        description:
          'Calamari with shredded lettuce, tomato, and homemade sweet chili sauce. Served with fried green plantains.',
        price: 12,
      },
      {
        id: 'coctel-camarones',
        name: 'Coctel de Camarones',
        description: 'Shrimp cocktail.',
        price: 13.5,
      },
      {
        id: 'ceviche-pupusa-loca',
        name: 'Ceviche Pupusa Loca',
        description: 'Shrimp, octopus, calamari, crab, and mussels ceviche with tortilla chips and avocado.',
        price: 16,
      },
      {
        id: 'ceviche-camarones',
        name: 'Ceviche de Camarones',
        description: 'Shrimp ceviche.',
        price: 14,
      },
      {
        id: 'alitas-pollo',
        name: 'Alitas de Pollo',
        description: 'Chicken wings with french fries.',
        price: 11.5,
      },
      {
        id: 'quesadillas',
        name: 'Quesadillas de Pollo / Carne',
        description: 'Chicken or beef quesadilla.',
        price: 13,
      },
      {
        id: 'nachos-guacamole',
        name: 'Nachos con Guacamole',
        description: 'Homemade guacamole with chips.',
        price: 10.5,
      },
      {
        id: 'yuca-chicharron',
        name: 'Yuca con Chicharron',
        description: 'Fried cassava and pork crackling.',
        price: 12,
      },
      {
        id: 'mini-picada',
        name: 'Mini Picada',
        description: 'Sausage, chicharron, and fried cassava.',
        price: 10.25,
      },
      {
        id: 'conchas-ajillo-vino',
        name: 'Conchas al Ajillo o al Vino Blanco',
        description: 'Clams in garlic or white wine sauce.',
        price: 18.95,
      },
      {
        id: 'conchas-frescas-6',
        name: 'Conchas Frescas x6',
        description: 'Fresh clams on the half shell.',
        price: 12,
      },
      {
        id: 'conchas-frescas-12',
        name: 'Conchas Frescas x12',
        description: 'Fresh clams on the half shell.',
        price: 18,
      },
    ],
  },
  {
    id: 'ensaladas',
    title: 'Ensaladas',
    note: 'Served with house dressing.',
    items: [
      {
        id: 'ensalada-pupusa-loca',
        name: 'Ensalada Pupusa Loca',
        description:
          'Lettuce, tomatoes, onions, cucumber, shredded carrots, spring mix, avocado, grilled steak, chicken, and shrimp.',
        price: 16.95,
      },
      {
        id: 'ensalada-mar',
        name: 'Ensalada de Mar',
        description:
          'Fried calamari and shrimp over lettuce, tomatoes, onions, cucumber, shredded carrots, avocado, and spring mix.',
        price: 16.25,
      },
      {
        id: 'ensalada-mixta',
        name: 'Ensalada Mixta',
        description: 'Lettuce, tomatoes, onions, cucumber, shredded carrot, spring mix, and avocado.',
        price: 10,
      },
      {
        id: 'ensalada-tropical',
        name: 'Ensalada Tropical',
        description: 'Mango, strawberry, lettuce, and spring mix with homemade dressing.',
        price: 11.25,
      },
      {
        id: 'ensalada-pollo',
        name: 'Ensalada de Pollo',
        description: 'Grilled chicken over lettuce, tomatoes, onions, cucumber, shredded carrots, and avocado.',
        price: 12.5,
      },
      {
        id: 'ensalada-carne',
        name: 'Ensalada de Carne',
        description: 'Grilled steak over lettuce, tomatoes, onions, cucumber, shredded carrots, and avocado.',
        price: 12.5,
      },
      {
        id: 'ensalada-camarones',
        name: 'Ensalada de Camarones',
        description: 'Grilled shrimp over lettuce, tomatoes, onions, cucumber, shredded carrots, and avocado.',
        price: 13.5,
      },
      {
        id: 'ensalada-mar-tierra',
        name: 'Ensalada Mar & Tierra',
        description: 'Grilled shrimp and skirt steak over lettuce, tomatoes, onions, cucumber, carrots, and avocado.',
        price: 17.25,
      },
    ],
  },
  {
    id: 'pollo',
    title: 'Pollo',
    note: 'Served with 2 sides.',
    items: [
      {
        id: 'pollo-asado',
        name: '1/2 Pollo Asado',
        description: 'Half grilled chicken.',
        price: 13.95,
      },
      {
        id: 'pollo-encebollado',
        name: '1/2 Pollo Encebollado',
        description: 'Half chicken with sauteed grilled onions.',
        price: 13,
      },
      {
        id: 'pechuga-hongos',
        name: 'Pechuga en Salsa de Hongos',
        description: 'Grilled chicken breast topped with mushroom cream sauce.',
        price: 16.95,
      },
      {
        id: 'pechuga-salteada',
        name: 'Pechuga Salteada',
        description: 'Sauteed grilled chicken strips with onions, peppers, and tomatoes.',
        price: 14.95,
      },
      {
        id: 'pechuga-vino-blanco',
        name: 'Pechuga al Vino Blanco',
        description: 'Grilled chicken breast in white wine sauce.',
        price: 17,
      },
      {
        id: 'pechuga-rellena-hongos',
        name: 'Pechuga Rellena en Salsa de Hongos',
        description: 'Stuffed chicken breast with ham and cheese, topped with mushroom sauce.',
        price: 17.5,
      },
      {
        id: 'pechuga-camarones',
        name: 'Pechuga con Camarones',
        description: 'Chicken breast and shrimp in garlic sauce or white wine sauce.',
        price: 22,
      },
      {
        id: 'pechuga-plancha',
        name: 'Pechuga a la Plancha',
        description: 'Grilled chicken breast.',
        price: 15,
      },
      {
        id: 'pechuga-empanizada',
        name: 'Pechuga Empanizada',
        description: 'Breaded chicken breast.',
        price: 16,
      },
      {
        id: 'pechuga-parmesana',
        name: 'Pechuga Parmesana',
        description: 'Chicken parmesan.',
        price: 16.95,
      },
      {
        id: 'arroz-pollo',
        name: 'Arroz con Pollo',
        description: 'Sauteed rice with chicken.',
        price: 15.25,
      },
    ],
  },
  {
    id: 'carnes',
    title: 'Carnes',
    note: 'Served with 2 sides.',
    items: [
      {
        id: 'carne-asada',
        name: 'Carne Asada',
        description: 'Grilled steak.',
        price: 15.95,
      },
      {
        id: 'bistec-encebollado',
        name: 'Bistec Encebollado',
        description: 'Grilled steak with sauteed onions.',
        price: 16.95,
      },
      {
        id: 'bistec-salteado',
        name: 'Bistec Salteado',
        description: 'Sauteed grilled steak strips.',
        price: 17.25,
      },
      {
        id: 'churrasco',
        name: 'Churrasco',
        description: 'Grilled skirt steak.',
        price: 29.5,
      },
      {
        id: 't-bone-steak',
        name: 'T-Bone Steak',
        description: 'T-bone steak with any 2 sides.',
        price: 19.95,
      },
      {
        id: 'bistec-relleno',
        name: 'Bistec Relleno en Salsa de Hongos',
        description: 'Stuffed steak with ham and cheese, topped with mushroom sauce.',
        price: 17.5,
      },
      {
        id: 'steak-guanaco',
        name: 'Steak Guanaco',
        description: 'T-bone steak with grilled onions, tomato, rice, sweet plantains, peppers, mushrooms, and avocado.',
        price: 22,
      },
      {
        id: 'steak-chapin',
        name: 'Steak Chapin',
        description: 'Sauteed grilled onions, tomato, peppers, mushrooms, chimol, avocado, and casamiento.',
        price: 22,
      },
      {
        id: 'steak-catracho',
        name: 'Steak Catracho',
        description: 'T-bone steak with mushrooms, tomato sauce, chimol, casamiento, and avocado.',
        price: 22,
      },
      {
        id: 'lomo-hongos',
        name: 'Lomo en Salsa de Hongos',
        description: 'Grilled pork loin topped with mushroom sauce.',
        price: 15,
      },
      {
        id: 'lomo-asado',
        name: 'Lomo de Cerdo Asado',
        description: 'Grilled pork loin.',
        price: 14.25,
      },
      {
        id: 'lomo-empanizado',
        name: 'Lomo Empanizado',
        description: 'Breaded pork loin.',
        price: 14.5,
      },
      {
        id: 'parrillada-carnes',
        name: 'Parrillada de Carnes',
        description: 'Grilled steak, chicken breast, sausage, and pork loin with fried green plantains and white rice.',
        price: 24.5,
      },
      {
        id: 'chuleta-grilled',
        name: 'Chuleta Asada',
        description: 'Grilled pork chop with sauteed onions, peppers, and tomatoes.',
        price: 14.95,
      },
      {
        id: 'chuleta-frita',
        name: 'Chuleta Frita',
        description: 'Fried pork chop with sauteed onions, peppers, and tomatoes.',
        price: 15,
      },
      {
        id: 'bandeja-paisa',
        name: 'Bandeja Paisa',
        description: 'Grilled steak, sausage, pork crackling, sweet plantains, white rice, eggs, avocado, and beans.',
        price: 25,
      },
    ],
  },
  {
    id: 'mariscos',
    title: 'Mariscos',
    note: 'Served with 2 sides.',
    items: [
      {
        id: 'salmon-ajillo',
        name: 'Salmon al Ajillo con Vegetales',
        description: 'Salmon in garlic sauce with vegetables.',
        price: 17.5,
      },
      {
        id: 'camarones-empanizados',
        name: 'Camarones Empanizados',
        description: 'Breaded shrimp.',
        price: 16,
      },
      {
        id: 'pargo-frito',
        name: 'Pargo Frito',
        description: 'Fried red snapper.',
        price: 18.95,
      },
      {
        id: 'mojarra-encebollada',
        name: 'Mojarra Encebollada',
        description: 'Sauteed tilapia with grilled onions, tomato, and peppers.',
        price: 17.5,
      },
      {
        id: 'mojarra-frita',
        name: 'Mojarra Frita',
        description: 'Fried tilapia.',
        price: 17.95,
      },
      {
        id: 'salmon-parrilla',
        name: 'Salmon a la Parrilla con Vegetales',
        description: 'Grilled salmon with vegetables.',
        price: 17.5,
      },
      {
        id: 'filete-ajillo',
        name: 'Filete al Ajillo',
        description: 'Fish fillet in garlic sauce.',
        price: 17,
      },
      {
        id: 'filete-empanizado',
        name: 'Filete Empanizado',
        description: 'Breaded fish fillet.',
        price: 16.25,
      },
      {
        id: 'filete-hongos',
        name: 'Filete Empanizado en Salsa de Hongos',
        description: 'Breaded fish fillet topped with mushroom cream sauce.',
        price: 16.5,
      },
      {
        id: 'langosta-rellena',
        name: 'Langosta Rellena',
        description: 'Stuffed lobster.',
        price: 70,
      },
      {
        id: 'cola-langosta',
        name: 'Cola de Langosta',
        description: 'Lobster tail.',
        price: 45,
      },
      {
        id: 'camarones-vino-ajillo',
        name: 'Camarones al Vino Blanco o al Ajillo',
        description: 'Shrimp in garlic sauce or white wine sauce.',
        price: 17,
      },
      {
        id: 'camarones-parmesana',
        name: 'Camarones Parmesana',
        description: 'Parmesan shrimp.',
        price: 17.95,
      },
      {
        id: 'camarones-enchilados',
        name: 'Camarones Enchilados',
        description: 'Sauteed shrimp in spicy tomato sauce.',
        price: 16.25,
      },
      {
        id: 'arroz-camarones',
        name: 'Arroz con Camarones',
        description: 'Sauteed rice with shrimp.',
        price: 17,
      },
      {
        id: 'filete-camarones',
        name: 'Filete con Camarones Empanizados',
        description: 'Breaded fish fillet and breaded shrimp.',
        price: 18,
      },
    ],
  },
  {
    id: 'especiales',
    title: 'Platos Especiales',
    note: 'House specials.',
    items: [
      {
        id: 'especial-dia',
        name: 'Especial del Dia',
        description: 'Daily special.',
        price: 10,
      },
      {
        id: 'combinado',
        name: 'Combinado',
        description: 'Grilled skirt steak, grilled chicken breast, and garlic shrimp with fried green plantains and rice.',
        price: 26,
      },
      {
        id: 'picada-loca-medium',
        name: 'Picada Loca Medium',
        description:
          'Grilled steak and chicken strips, sausage, pork crackling, fried cassava, green plantains, grill loin, sweet plantain, vegetables, and cucumbers.',
        price: 40,
      },
      {
        id: 'picada-loca-large',
        name: 'Picada Loca Grande',
        description:
          'Grilled steak and chicken strips, sausage, pork crackling, fried cassava, green plantains, grill loin, sweet plantain, vegetables, and cucumbers.',
        price: 55,
      },
      {
        id: 'gallina-asada',
        name: 'Gallina Asada',
        description: 'Half grilled chicken, rice, salad, and small soup.',
        price: 17.95,
      },
      {
        id: 'mar-y-tierra',
        name: 'Mar y Tierra',
        description: 'Grilled skirt steak and shrimp on a hot plate.',
        price: 30,
      },
    ],
  },
  {
    id: 'sides',
    title: 'Acompanantes',
    note: 'Sides.',
    items: [
      {
        id: 'arroz-blanco',
        name: 'Arroz Blanco',
        description: 'White rice.',
        price: 3,
      },
      {
        id: 'arroz-amarillo',
        name: 'Arroz Amarillo',
        description: 'Yellow rice.',
        price: 3.5,
      },
      {
        id: 'casamiento',
        name: 'Casamiento',
        description: 'Rice and beans mixed.',
        price: 3.5,
      },
      {
        id: 'habichuelas',
        name: 'Habichuelas',
        description: 'Red beans.',
        price: 3.5,
      },
      {
        id: 'frijol-frito',
        name: 'Frijol Frito',
        description: 'Fried beans.',
        price: 3.5,
      },
      {
        id: 'platanos-maduros',
        name: 'Platanos Maduros',
        description: 'Sweet plantains.',
        price: 3.5,
      },
      {
        id: 'tostones',
        name: 'Tostones',
        description: 'Fried green plantains.',
        price: 3.5,
      },
      {
        id: 'yuca-frita',
        name: 'Yuca Frita',
        description: 'Fried cassava.',
        price: 3.5,
      },
      {
        id: 'papas-fritas',
        name: 'Papas Fritas',
        description: 'French fries.',
        price: 3.5,
      },
      {
        id: 'vegetales',
        name: 'Vegetales',
        description: 'Vegetables.',
        price: 5,
      },
      {
        id: 'aguacate',
        name: 'Aguacate',
        description: 'Avocado side.',
        price: 3.95,
      },
      {
        id: 'ensalada-pequena',
        name: 'Ensalada Pequena',
        description: 'Side salad.',
        price: 3.5,
      },
    ],
  },
  {
    id: 'kids-sandwiches',
    title: 'Kids & Sandwiches',
    note: 'Family-friendly items.',
    items: [
      {
        id: 'chicken-fingers',
        name: 'Chicken Fingers',
        description: 'Breaded chicken strips.',
        price: 10,
      },
      {
        id: 'salchipapa',
        name: 'Salchipapa',
        description: 'Fried hot dog bits with french fries.',
        price: 9.25,
      },
      {
        id: 'steak-tiritas',
        name: 'Steak Tiritas',
        description: 'Grilled steak strips and french fries.',
        price: 10.25,
      },
      {
        id: 'sandwich-pollo',
        name: 'Sandwich de Pollo',
        description: 'Chicken sandwich with french fries, lettuce, tomatoes, onions, and mayo. Add cheese for $1.',
        price: 11.25,
      },
      {
        id: 'sandwich-carne',
        name: 'Sandwich de Carne',
        description: 'Steak sandwich with french fries, lettuce, tomatoes, onions, and mayo. Add cheese for $1.',
        price: 11.5,
      },
      {
        id: 'sandwich-parmesana',
        name: 'Sandwich de Pechuga Parmesana',
        description: 'Chicken parmesan sandwich with french fries.',
        price: 11.75,
      },
      {
        id: 'sandwich-jamon-queso',
        name: 'Sandwich de Jamon y Queso',
        description: 'Ham and cheese sandwich with french fries, lettuce, tomatoes, onions, and mayo.',
        price: 11.25,
      },
    ],
  },
  {
    id: 'desserts-drinks',
    title: 'Desserts & Drinks',
    note: 'Desserts, shakes, juices, sodas, and hot drinks.',
    items: [
      {
        id: 'postres-grande',
        name: 'Postres Grande',
        description: 'Large desserts.',
        price: 7,
      },
      {
        id: 'tres-leches',
        name: 'Tres Leches',
        description: 'Tres leches cake.',
        price: 6,
      },
      {
        id: 'tiramisu',
        name: 'Tiramisu',
        description: 'Tiramisu.',
        price: 6,
      },
      {
        id: 'flan',
        name: 'Flan',
        description: 'Flan.',
        price: 6,
      },
      {
        id: 'arroz-leche',
        name: 'Arroz con Leche',
        description: 'Rice pudding.',
        price: 5,
      },
      {
        id: 'mangos',
        name: 'Mangos',
        description: 'Mango dessert.',
        price: 5,
      },
      {
        id: 'empanada-platano-dessert',
        name: 'Empanada de Platano',
        description: 'Plantain empanada.',
        price: 6,
      },
      {
        id: 'horchata',
        name: 'Horchata',
        description: 'House horchata.',
        price: 5,
      },
      {
        id: 'horchata-large',
        name: 'Horchata Large',
        description: 'Large horchata.',
        price: 8,
      },
      {
        id: 'horchata-pitcher',
        name: 'Horchata Pitcher',
        description: 'Pitcher of horchata.',
        price: 18,
      },
      {
        id: 'soda-cans',
        name: 'Soda Cans',
        description: 'Canned soda.',
        price: 2,
      },
      {
        id: 'soda-bottles',
        name: 'Soda Bottles',
        description: 'Bottled soda.',
        price: 2.15,
      },
      {
        id: 'inca-cola-can',
        name: 'Inca Cola Can',
        description: 'Canned Inca Cola.',
        price: 2.5,
      },
      {
        id: 'inca-cola-bottle',
        name: 'Inca Cola Bottle',
        description: 'Bottled Inca Cola.',
        price: 2,
      },
      {
        id: 'maranon',
        name: 'Maranon',
        description: 'Cashew fruit drink.',
        price: 5,
      },
      {
        id: 'maranon-large',
        name: 'Maranon Large',
        description: 'Large cashew fruit drink.',
        price: 7.25,
      },
      {
        id: 'tamarindo',
        name: 'Tamarindo',
        description: 'Tamarind drink.',
        price: 5,
      },
      {
        id: 'tamarindo-large',
        name: 'Tamarindo Large',
        description: 'Large tamarind drink.',
        price: 7.25,
      },
      {
        id: 'cebada',
        name: 'Cebada',
        description: 'Cebada drink.',
        price: 5,
      },
      {
        id: 'cebada-large',
        name: 'Cebada Large',
        description: 'Large cebada drink.',
        price: 7.25,
      },
      {
        id: 'batido-agua-leche',
        name: 'Batido en Agua o Leche',
        description: 'Fresa, mango, papaya, banano, pina, maracuya, guanabana, or combinado.',
        price: 6,
      },
      {
        id: 'jugo-naranja',
        name: 'Jugo de Naranja Natural',
        description: 'Organic orange juice.',
        price: 6,
      },
      {
        id: 'morir-sonando',
        name: 'Morir Sonando',
        description: 'Orange juice and milk.',
        price: 6,
      },
      {
        id: 'limonada',
        name: 'Limonada',
        description: 'Lemonade.',
        price: 6.15,
      },
      {
        id: 'cafe-negro',
        name: 'Cafe Negro',
        description: 'Black coffee.',
        price: 2,
      },
      {
        id: 'cafe-leche',
        name: 'Cafe con Leche',
        description: 'Coffee with milk.',
        price: 2.25,
      },
      {
        id: 'capuchino',
        name: 'Capuchino',
        description: 'Cappuccino.',
        price: 3.25,
      },
      {
        id: 'chocolate-caliente',
        name: 'Chocolate Caliente',
        description: 'Hot chocolate.',
        price: 3.25,
      },
      {
        id: 'espresso',
        name: 'Espresso',
        description: 'Espresso.',
        price: 1.5,
      },
      {
        id: 'atol-elote-small',
        name: 'Atol de Elote Small',
        description: 'Small corn atol.',
        price: 5,
      },
      {
        id: 'atol-elote-large',
        name: 'Atol de Elote Large',
        description: 'Large corn atol.',
        price: 7.25,
      },
      {
        id: 'kids-nesquik',
        name: 'Fresa Chocolate',
        description: 'Kids Nesquik drink.',
        price: 2,
      },
      {
        id: 'kids-tropicana',
        name: 'Tropicana Jugo',
        description: 'Orange or apple juice.',
        price: 2,
      },
    ],
  },
  {
    id: 'bar',
    title: 'Cocktails & Beer',
    note: 'Alcohol orders require age verification and restaurant confirmation.',
    items: [
      {
        id: 'pina-colada',
        name: 'Pina Colada',
        description: 'Coconut, pineapple, and rum. Virgin option available.',
        price: 14,
      },
      {
        id: 'mojitos',
        name: 'Mojitos',
        description: 'Mint, lime juice, sugar, and rum. Strawberry, mango, passion fruit, coconut, or traditional.',
        price: 13,
      },
      {
        id: 'michelada',
        name: 'Michelada',
        description: 'Beer, lime juice, spices, and chili.',
        price: 12,
      },
      {
        id: 'blue-long-island',
        name: 'Blue Long Island',
        description: 'Vodka, rum, gin, tequila, blue curacao, and sour mix.',
        price: 14,
      },
      {
        id: 'long-island',
        name: 'Long Island Iced Tea',
        description: 'Vodka, rum, gin, tequila, triple sec, cola, and lemon.',
        price: 14,
      },
      {
        id: 'michelada-loca',
        name: 'Michelada Loca',
        description: 'Michelada with Modelo beer and cocktail shrimp garnish.',
        price: 15,
      },
      {
        id: 'margarita-loca',
        name: 'Margarita Loca',
        description: 'Margarita with Grand Marnier and a chilled beer.',
        price: 18,
      },
      {
        id: 'margarita-frozen',
        name: 'Frozen Margarita',
        description: 'Strawberry, mango, passion fruit, coconut, lemon, pineapple, or classic.',
        price: 16,
      },
      {
        id: 'margarita-rocks',
        name: 'Margarita on the Rocks',
        description: 'Strawberry, mango, passion fruit, coconut, lemon, pineapple, or classic.',
        price: 14,
      },
      {
        id: 'margarita-doble',
        name: 'Margarita Doble',
        description: 'Strawberry, mango, passion fruit, coconut, lemon, pineapple, or classic.',
        price: 25,
      },
      {
        id: 'red-sangria-pitcher',
        name: 'Red Sangria Pitcher',
        description: 'Pitcher of red sangria.',
        price: 32,
      },
      {
        id: 'red-sangria-glass',
        name: 'Red Sangria Glass',
        description: 'Glass of red sangria.',
        price: 12,
      },
      {
        id: 'passion-sangria-pitcher',
        name: 'Passion Fruit Sangria Pitcher',
        description: 'Pitcher of passion fruit sangria.',
        price: 33,
      },
      {
        id: 'passion-sangria-glass',
        name: 'Passion Fruit Sangria Glass',
        description: 'Glass of passion fruit sangria.',
        price: 13,
      },
      {
        id: 'beer',
        name: 'Beer',
        description: 'Coors Light, Famosas, Modelo, Corona, or Heineken.',
        price: 6,
      },
      {
        id: 'cubetazo',
        name: 'Cubetazo',
        description: 'Beer bucket.',
        price: 24,
      },
    ],
  },
]
