export const deliveryLinks = {
  uberEats:
    'https://www.ubereats.com/search?q=La%20Pupusa%20Loca%205910%20Bergenline%20Ave%20West%20New%20York%20NJ',
  doorDash:
    'https://www.doordash.com/search/store/La%20Pupusa%20Loca%205910%20Bergenline%20Ave%20West%20New%20York%20NJ/',
  grubhub: 'https://www.grubhub.com/restaurant/la-pupusa-loca-5910-bergenline-ave-west-new-york/10008728',
}

export const menuCategories = [
  {
    id: 'acompanantes',
    title: 'Acompanantes',
    note: 'Sides.',
    items: [
      {
        id: 'maduros',
        image: 'Pupusa Loca Menu Images/fried-sweet-plantains Background Removed.jpg_202606110117.png',
        name: 'Maduros',
        description: 'Sweet plantains.',
        price: 3.5,
      },
    ],
  },
  {
    id: 'aperitivos',
    title: 'Aperitivos',
    note: 'Appetizers and shareables.',
    items: [
      {
        id: 'baleada-con-todo',
        image: 'Pupusa Loca Menu Images/baleadas-con-todo Background Removed.jpg_202606110118.png',
        name: 'Baleadas con Todo',
        description: 'Fried beans, scrambled eggs, sour cream, cheese, steak strips, and avocado.',
        price: 6.95,
      },
      {
        id: 'guacamole-tajadas',
        image: 'Pupusa Loca Menu Images/guacamole-con-tajadas Background Removed.jpg_202606110117.png',
        name: 'Guacamole con Tajadas',
        description: 'Guacamole with green plantain chips.',
        price: 10.5,
      },
      {
        id: 'pastelitos-pollo-3',
        image: 'Pupusa Loca Menu Images/pastelitos-de-pollo-3 Background Removed.jpg_202606110116.png',
        name: 'Pastelitos de Pollo (3)',
        description: 'Three chicken patties.',
        price: 5.25,
      },
      {
        id: 'picadera-mixta-sm',
        image: 'Pupusa Loca Menu Images/picadera-mixta-sm Background Removed.jpg_202606110116.png',
        name: 'Picadera Mixta Sm',
        description: 'Small mixed platter.',
        price: 40,
      },
      {
        id: 'platanos-crema',
        image: 'Pupusa Loca Menu Images/platanos-con-crema Background Removed.jpg_202606110116.png',
        name: 'Platanos con Crema',
        description: 'Sweet plantains with sour cream.',
        price: 5,
      },
      {
        id: 'pupusa-chicharron',
        name: 'Pupusa Chicharron',
        description: 'Pork pupusa.',
        price: 2.75,
      },
      {
        id: 'pupusa-chicharron-harina-arroz',
        name: 'Pupusa Chicharron Harina Arroz',
        description: 'Pork pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-frijol',
        name: 'Pupusa Frijol',
        description: 'Bean pupusa.',
        price: 2.75,
      },
      {
        id: 'pupusa-frijol-harina-arroz',
        name: 'Pupusa Frijol Harina Arroz',
        description: 'Bean pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-frijol-queso',
        name: 'Pupusa Frijol y Queso',
        description: 'Bean and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-frijol-queso-harina-arroz',
        name: 'Pupusa Frijol y Queso Harina Arroz',
        description: 'Bean and cheese pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-loroco',
        name: 'Pupusa Loroco',
        description: 'Loroco and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-loroco-harina-arroz',
        name: 'Pupusa Loroco Harina Arroz',
        description: 'Loroco and cheese pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-queso',
        name: 'Pupusa Queso',
        description: 'Cheese pupusa.',
        price: 2.75,
      },
      {
        id: 'pupusa-queso-harina-arroz',
        name: 'Pupusa Queso Harina Arroz',
        description: 'Cheese pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-revuelta',
        image: 'Pupusa Loca Menu Images/pupusa-revuelta Background Removed.jpg_202606110116.png',
        name: 'Pupusa Revuelta',
        description: 'Pork, bean, and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-revuelta-harina-arroz',
        name: 'Pupusa Revuelta Harina Arroz',
        description: 'Pork, bean, and cheese pupusa - rice flour.',
        price: 3.5,
      },
      {
        id: 'pupusa-de-ayote',
        name: 'Pupusa De Ayote',
        description: 'Zucchini and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-de-camaron',
        name: 'Pupusa De Camaron',
        description: 'Shrimp and cheese pupusa.',
        price: 3.5,
      },
      {
        id: 'pupusa-de-chorizo',
        name: 'Pupusa De Chorizo',
        description: 'Chorizo and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-de-jalapeno',
        name: 'Pupusa De Jalapeño',
        description: 'Jalapeno and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-de-pollo',
        name: 'Pupusa De Pollo',
        description: 'Chicken and cheese pupusa.',
        price: 3,
      },
      {
        id: 'pupusa-llena-de-amor',
        name: 'Pupusa Llena De Amor',
        description: 'Pupusa filled with love.',
        price: 5,
      },
      {
        id: 'pupusa-mixta',
        name: 'Pupusa Mixta',
        description: 'Mixed pupusa.',
        price: 3.5,
      },
      {
        id: 'pupusa-sliders',
        name: 'Pupusa Sliders',
        description: 'Mini pupusa sliders.',
        price: 8,
      },
    ],
  },
  {
    id: 'batidos',
    title: 'Batidos',
    note: 'Fresh fruit shakes.',
    items: [
      {
        id: 'batido-mango',
        image: 'Pupusa Loca Menu Images/batido-mango Background Removed.jpg_202606110117.png',
        name: 'Batido Mango',
        description: 'Mango shake.',
        price: 6,
      },
    ],
  },
  {
    id: 'bebidas-calientes',
    title: 'Bebidas Calientes',
    note: 'Hot drinks.',
    items: [
      {
        id: 'atol-elote',
        image: 'Pupusa Loca Menu Images/atol-de-elote Background Removed.jpg_202606110117.png',
        name: 'Atol de Elote',
        description: 'Sweet corn drink.',
        price: 5,
      },
      {
        id: 'chocolate-caliente',
        image: 'Pupusa Loca Menu Images/chocolate-caliente Background Removed.jpg_202606110117.png',
        name: 'Chocolate Caliente',
        description: 'Hot chocolate.',
        price: 3.25,
      },
      {
        id: 'atol-elote-grande',
        image: 'Pupusa Loca Menu Images/atol-de-elote Background Removed.jpg_202606110117.png',
        name: 'Atol de Elote Grande',
        description: 'Large sweet corn drink.',
        price: 7.25,
      },
    ],
  },
  {
    id: 'camarones',
    title: 'Camarones',
    note: 'Shrimp entrees.',
    items: [
      {
        id: 'camarones-asados',
        image: 'Pupusa Loca Menu Images/camarones-asados Background Removed.jpg_202606110117.png',
        name: 'Camarones Asados',
        description: 'Grilled shrimp.',
        price: 17,
      },
    ],
  },
  {
    id: 'carnes',
    title: 'Carnes',
    note: 'Meat entrees.',
    items: [
      {
        id: 'bistec-palomilla',
        image: 'Pupusa Loca Menu Images/bistec-de-palomilla Background Removed.jpg_202606110117.png',
        name: 'Bistec de Palomilla',
        description: 'Palomilla steak.',
        price: 16.95,
      },
      {
        id: 'churrasco',
        image: 'Pupusa Loca Menu Images/churrasco Background Removed.jpg_202606110117.png',
        name: 'Churrasco',
        description: 'Grilled skirt steak.',
        price: 29.5,
      },
      {
        id: 'mar-y-tierra',
        image: 'Pupusa Loca Menu Images/mar-y-tierra Background Removed.jpg_202606110116.png',
        name: 'Mar y Tierra',
        description: 'Grilled skirt steak and shrimp.',
        price: 30,
      },
    ],
  },
  {
    id: 'combinaciones-dia',
    title: 'Combinaciones del Dia',
    note: 'Daily combinations.',
    items: [
      {
        id: 'bandeja-paisa',
        image: 'Pupusa Loca Menu Images/bandeja-paisa Background Removed.jpg_202606110118.png',
        name: 'Bandeja Paisa',
        description: 'Grilled steak, sausage, pork crackling, sweet plantains, white rice, eggs, avocado, and beans.',
        price: 25,
      },
      {
        id: 'plato-tipico-salvadoreno',
        image: 'Pupusa Loca Menu Images/plato-tipico-salvadoreno Background Removed.jpg_202606110116.png',
        name: 'Plato Tipico Salvadoreno',
        description: 'Typical Salvadoran platter.',
        price: 16,
      },
    ],
  },
  {
    id: 'desayunos',
    title: 'Desayunos',
    note: 'Breakfast plates.',
    items: [
      {
        id: 'fourth-july-pancakes',
        image: 'Pupusa Loca Menu Images/4th-of-july-pancakes Background Removed.jpg_202606110118.png',
        name: '4th of July Pancakes',
        description: 'Independence Day pancakes.',
        price: 10,
      },
      {
        id: 'big-breakfast',
        image: 'Pupusa Loca Menu Images/big-breakfast Background Removed.jpg_202606110118.png',
        name: 'Big Breakfast',
        description: 'Big breakfast plate.',
        price: 12,
      },
      {
        id: 'desayuno-con-tamal',
        image: 'Pupusa Loca Menu Images/desayuno-con-tamal Background Removed.jpg_202606110117.png',
        name: 'Desayuno con Tamal',
        description: 'Breakfast with tamale.',
        price: 11,
      },
      {
        id: 'desayuno-salvadoreno',
        image: 'Pupusa Loca Menu Images/desayuno-salvadoreno Background Removed.jpg_202606110117.png',
        name: 'Desayuno Salvadoreno',
        description: 'Eggs, beans, plantains, avocado, cheese, and tortilla.',
        price: 11.25,
      },
      {
        id: 'desayuno-tipico-carne',
        image: 'Pupusa Loca Menu Images/desayuno-tipico-con-carne Background Removed.jpg_202606110117.png',
        name: 'Desayuno Tipico con Carne',
        description: 'Typical breakfast with meat.',
        price: 12,
      },
      {
        id: 'fruity-pebbles-waffles',
        image: 'Pupusa Loca Menu Images/fruity-pebbles-waffles Background Removed.jpg_202606110117.png',
        name: 'Fruity Pebbles Waffles',
        description: 'Waffles with Fruity Pebbles.',
        price: 10,
      },
      {
        id: 'huevos-revueltos-pupusa',
        name: 'Huevos Revueltos con Pupusa',
        description: 'Scrambled eggs with pupusa.',
        price: 11,
      },
      {
        id: 'pancake-lovers-dream',
        image: 'Pupusa Loca Menu Images/pancake-lovers-dream Background Removed.jpg_202606110116.png',
        name: 'Pancake Lover\'s Dream',
        description: 'Assorted pancakes platter.',
        price: 12,
      },
      {
        id: 'strawberry-shortcake-waffles',
        image: 'Pupusa Loca Menu Images/strawberry-shortcake-waffles Background Removed.jpg_202606110115.png',
        name: 'Strawberry Shortcake Waffles',
        description: 'Waffles with strawberries and cream.',
        price: 10,
      },
      {
        id: 'chunky-monkey-pancakes',
        image: 'Pupusa Loca Menu Images/chuncky-monkey-pancakes Background Removed.jpg_202606110117.png',
        name: 'Chunky Monkey Pancakes',
        description: 'Banana, chocolate chip, and nut pancakes.',
        price: 10,
      },
    ],
  },
  {
    id: 'ensaladas',
    title: 'Ensaladas',
    note: 'Fresh salads.',
    items: [
      {
        id: 'ensalada-mar-tierra',
        image: 'Pupusa Loca Menu Images/ensalada-mar-y-tierra Background Removed.jpg_202606110117.png',
        name: 'Ensalada Mar y Tierra',
        description: 'Grilled shrimp and steak salad.',
        price: 17.25,
      },
    ],
  },
  {
    id: 'jugos-naturales',
    title: 'Jugos Naturales',
    note: 'Natural juices and drinks.',
    items: [
      {
        id: 'jugo-natural-horchata',
        image: 'Pupusa Loca Menu Images/jugo-natural-horchata Background Removed.jpg_202606110116.png',
        name: 'Jugo Natural Horchata',
        description: 'House horchata drink.',
        price: 5,
      },
    ],
  },
  {
    id: 'mariscos',
    title: 'Mariscos',
    note: 'Seafood entrees.',
    items: [
      {
        id: 'langosta-rellena-camarones',
        image: 'Pupusa Loca Menu Images/langosta-rellena-con-camarones Background Removed.jpg_202606110116.png',
        name: 'Langosta Rellena con Camarones',
        description: 'Stuffed lobster with shrimp.',
        price: 70,
      },
    ],
  },
  {
    id: 'menu-ninos',
    title: 'Menu Ninos',
    note: 'Kids menu.',
    items: [
      {
        id: 'trocitos-carne-pupusa',
        name: 'Trocitos de Carne con Pupusa',
        description: 'Steak bits with pupusa.',
        price: 10.25,
      },
      {
        id: 'trocitos-pollo-papitas',
        image: 'Pupusa Loca Menu Images/Trocitos de Pollo Con Papitas Background Removed.png',
        name: 'Trocitos de Pollo con Papitas',
        description: 'Chicken bits with fries.',
        price: 9.25,
      },
    ],
  },
  {
    id: 'pollo',
    title: 'Pollo',
    note: 'Chicken entrees.',
    items: [
      {
        id: 'pechuga-hawaiana',
        image: 'Pupusa Loca Menu Images/pechuga-a-la-hawaiana Background Removed.jpg_202606110116.png',
        name: 'Pechuga a la Hawaiana',
        description: 'Hawaiian chicken breast.',
        price: 16.95,
      },
      {
        id: 'pechuga-plancha',
        image: 'Pupusa Loca Menu Images/pechuga-a-la-plancha Background Removed.jpg_202606110116.png',
        name: 'Pechuga a la Plancha',
        description: 'Grilled chicken breast.',
        price: 15,
      },
      {
        id: 'pechuga-champinones',
        image: 'Pupusa Loca Menu Images/pechuga-con-champinones Background Removed.jpg_202606110116.png',
        name: 'Pechuga con Champinones',
        description: 'Chicken breast with mushrooms.',
        price: 16.95,
      },
      {
        id: 'pollo-tajadas',
        image: 'Pupusa Loca Menu Images/pollo-con-tajadas Background Removed.jpg_202606110116.png',
        name: 'Pollo con Tajadas',
        description: 'Chicken with green plantain slices.',
        price: 15,
      },
    ],
  },
  {
    id: 'cerdo',
    title: 'CERDO',
    note: 'Pork entrees.',
    items: [
      {
        id: 'chuletas-cerdo',
        image: 'Pupusa Loca Menu Images/chuletas-de-cerdo Background Removed.jpg_202606110117.png',
        name: 'Chuletas de Cerdo',
        description: 'Pork chops.',
        price: 14.95,
      },
    ],
  },
  {
    id: 'postres',
    title: 'Postres',
    note: 'Desserts.',
    items: [
      {
        id: 'empanada-platano-3',
        image: 'Pupusa Loca Menu Images/empanada-de-platano-3 Background Removed.jpg_202606110117.png',
        name: 'Empanada de Platano (3)',
        description: 'Three plantain empanadas.',
        price: 6,
      },
      {
        id: 'oreo-cheesecake',
        image: 'Pupusa Loca Menu Images/oreo-cheesecake Background Removed.jpg_202606110117.png',
        name: 'Oreo Cheesecake',
        description: 'Oreo cheesecake.',
        price: 6,
      },
      {
        id: 'tiramisu',
        image: 'Pupusa Loca Menu Images/tiramisu Background Removed.jpg_202606110116.png',
        name: 'Tiramisu',
        description: 'Tiramisu.',
        price: 6,
      },
      {
        id: 'tres-leches',
        image: 'Pupusa Loca Menu Images/tres-leches Background Removed.jpg_202606110116.png',
        name: 'Tres Leches',
        description: 'Tres leches cake.',
        price: 6,
      },
    ],
  },
  {
    id: 'sandwiches',
    title: 'Sandwiches',
    note: 'Sandwiches.',
    items: [
      {
        id: 'panes-rellenos',
        image: 'Pupusa Loca Menu Images/panes-rellenos Background Removed.jpg_202606110116.png',
        name: 'Panes Rellenos',
        description: 'Stuffed Salvadoran sandwich.',
        price: 11.25,
      },
    ],
  },
  {
    id: 'sopas',
    title: 'Sopas',
    note: 'Soups served with tortillas or rice.',
    items: [
      {
        id: 'sopa-pollo',
        image: 'Pupusa Loca Menu Images/sopa-de-pollo Background Removed.jpg_202606110115.png',
        name: 'Sopa de Pollo',
        description: 'Chicken soup.',
        price: 11.25,
      },
      {
        id: 'sopa-res',
        image: 'Pupusa Loca Menu Images/sopa-de-res Background Removed.jpg_202606110115.png',
        name: 'Sopa de Res',
        description: 'Beef soup.',
        price: 11.25,
      },
    ],
  },
]
